name: bdns
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# --------------------------------- 
# requirements for building docs
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - jupyter
  - quarto
  - itables>2.4.0
  - pyfiglet
  - pandas
  - pip
  - pip:
    - bsdd
