[workspace]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
name = "BDNS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
check-duplicates = "python tools/check-duplicates.py"

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.1,<3"
pyfiglet = ">=1.0.3,<2"

[pypi-dependencies]
bsdd = ">=0.8.3, <0.9"
