name: Build docs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.13
        with:
            manifest-path: pixi.toml
            pixi-version: v0.49.0
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: | 
          quarto install tinytex
        shell: pixi run bash -e {0} # https://pixi.sh/latest/advanced/github_actions/#custom-shell-wrapper
      - run: quarto render .
        
      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site