# This workflow runs some checks on the abbreviation file 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BDNS validation checks

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  Check-Duplicates:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.13
        with:
            manifest-path: pixi.toml
            pixi-version: v0.49.0
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - run: pixi run check-duplicates

      - run: pixi run check-sort

      - run: pixi run check-ifc4_3

      - run: pixi run check-unique-ifc4_3-mappings